before_script:
  - pip install -r pip_install.txt


stages:
  - build
  - test


build_app:
  stage: build
  tags:
    - ubuntu
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=DEBUG ../
    - make -j2


test_app:
  stage: test
  tags:
    - ubuntu
  script:
    - python python/test.py
